openapi: 3.0.3
info:
  version: 1.0.0
  title: FCAgenda
  description:
    $ref: ./info-description.md
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Auth
    description: Rotas de autenticação.
  - name: Office
    description: Gerenciamento de escritórios.
  - name: Desk
    description: Gerenciamento de estações de trabalho.
  - name: Appointment
    description: Gerenciamento de agendamentos.
servers:
  - url: 'https://fcagenda.herokuapp.com'
paths:
  /auth/register:
    $ref: paths/auth/register.yaml
  /auth/verifyemail:
    $ref: paths/auth/verifyemail.yaml
  /auth/login:
    $ref: paths/auth/login.yaml
  /office/create:
    $ref: paths/office/create.yaml
  /office/update:
    $ref: paths/office/update.yaml
  /desk/update:
    $ref: paths/desk/update.yaml
  /office/list:
    $ref: paths/office/list.yaml
  /appointment/create:
    $ref: paths/appointment/create.yaml
  /desk/listdesks:
    $ref: paths/desk/listdesks.yaml
components:
  securitySchemes:
    Bearer Token:
      type: http
      scheme: bearer
      bearerFormat: JWT
